---
  HeatStacks.create_update_delete_stack:
    -
      args:
        template_path: "samples/tasks/scenarios/heat/templates/resource-group.yaml.template"
        updated_template_path: "samples/tasks/scenarios/heat/templates/updated-resource-group-reduce.yaml.template"
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 3
