---
  HeatStacks.create_and_delete_stack:
    -
      args:
        template_path: "samples/tasks/scenarios/heat/templates/resource-group-with-constraint.yaml.template"
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2