---
  CinderVolumes.create_volume_from_snapshot:
    -
      args:
          do_delete: true
      runner:
        type: "constant"
        times: 3
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2
        volumes:
          size: 1
